### ISSUE TITLE
pjclStatisticalRNG: RangeError: invalid array length

### ISSUE THREAD

**Issue by James-E-A** [fcorella/pjcl#1]
I'm trying to use this library on Firefox ESR, but one of the functions seems to be broken.

```js
import("https://cdn.jsdelivr.net/npm/pjcl@1.0.0/pjcl.js")
.then(pjcl => {
  console.info("A random byte:", pjcl.pjclStatisticalRNG(0n, 256n));
  }
).catch(error => {
    console.error(error);
});
```

> ```
> RangeError: invalid array length
>     pjclSub https://cdn.jsdelivr.net/npm/pjcl@1.0.0/pjcl.js:705
>     pjclStatisticalRNG https://cdn.jsdelivr.net/npm/pjcl@1.0.0/pjcl.js:2535
>     <anonymous> debugger eval code:3
>     promise callback* debugger eval code:2
> debugger eval code:6:13
> ```

(I get the same error even when downloading the source manually from GitHub; I only use cdnjs above for ease of reproduction.)

**Comment by wesdevpro** [comment]
Interesting! Thanks for submitting an issue.

**Comment by fcorella** [comment]
PJCL predates ECMAScript2020 and does not use the JavaScript BigInt type.  In PJCL, big integers are encoded as arrays of 24-bit limbs, list significant limb first, as described in section 2.2 of the documentation.  So to compute a statistically random number in the range 0 to 256, you call pjclStatisticalRNG([ ], [256]), where the empty array [ ] encodes the number 0, and the one-limb array [256] encodes the number 256.  By the way, if you had used pjcl-with-argument-checking.js instead of pjcl.js, the encoding error would have been caught by the argument checking performed by the function pjclStatisticalRNG, before the call to pjclSub.

**Comment by fcorella** [comment]
I'm closing this issue but opening two follow-up ones, asking for volunteers to write conversion routines between BigInt encodings and performance comparison tests.
